# Generated by Django 5.2.8 on 2025-11-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='Password',
            field=models.CharField(max_length=128),
        ),
    ]
